#!/bin/bash

# Nerd fonts is required, you just need to append your nerd font to *fonts[] in your config.h

bat="$(cat /sys/class/power_supply/BAT0/capacity)"

if (( $bat == 100 )); then
	echo ""

	elif (( $bat >= 90 )); then
		echo ""

	elif (( $bat >= 80 )); then
		echo ""

	elif (( $bat >= 70 )); then
		echo ""

	elif (( $bat >= 60 )); then
		echo ""

	elif (( $bat >= 50 )); then
		echo ""

	elif (( $bat >= 40 )); then
		echo ""

	elif (( $bat >= 30 )); then
		echo ""

	elif (( $bat >= 20 )); then
		echo ""

	elif (( $bat <= 10 )); then
		echo ""
fi
